services:
  db:
    image: postgres:latest
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  restservice.webapi:
    image: restservice.webapi
    build:
      context: .
      dockerfile: RestService.WebApi/Dockerfile
    env_file: .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data: