# This is a generated file. Not intended for manual editing.
services:
  restservice.webapi:
    build:
      context: "C:\\Users\\Anton\\Desktop\\RestService"
      dockerfile: "RestService.WebApi/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "restservice.webapi:dev"
    ports:
    - "127.0.0.1:57001:57000"
    - "127.0.0.1:57201:57200"
    - "127.0.0.1:57401:57400"
    volumes:
    - "C:\\Users\\Anton\\Desktop\\RestService\\RestService.WebApi:/app:rw"
    - "C:\\Users\\Anton\\Desktop\\RestService:/src:rw"
    - "C:\\Users\\Anton\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\Anton\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.3.3\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Users\\Anton\\AppData\\Local\\Programs\\Rider\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\Anton\\AppData\\Local\\JetBrains\\Rider2024.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_4_04_21_38_40:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
